language: ruby
rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
matrix:
  include:
    name: Rubinius
    rvm: rbx-3
    dist: trusty
  fast_finish: true
cache: bundler
before_install:
  - gem install bundler
